[package]
name = "related-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
related = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "repository_parsers"
path = "fuzz_targets/repository_parsers.rs"
test = false
doc = false
bench = false
